# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='type',
            field=models.IntegerField(choices=[(1, 'Math'), (5, 'English'), (2, 'Chemistry'), (4, 'Biology'), (3, 'Physics')]),
        ),
    ]
