# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20171102_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='API.Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='type',
            field=models.IntegerField(choices=[(3, 'Physics'), (4, 'Biology'), (2, 'Chemistry'), (1, 'Math'), (5, 'English')]),
        ),
    ]
